name: Build iOS libvosk.xcframework

on:
  workflow_dispatch:

jobs:
  build-ios-xcframework:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make build script executable
        run: chmod +x build_ios.sh

      - name: Install build dependencies
        run: |
          brew install autoconf automake libtool sox gcc
          echo "/opt/homebrew/opt/libtool/libexec/gnubin" >> $GITHUB_PATH

      - name: Build iOS libvosk.xcframework
        run: ./build_ios.sh

      - name: Compress XCFramework Artifact
        run: |
          cd dist/ios
          zip -r libvosk-ios-xcframework.zip libvosk.xcframework

      - name: Upload iOS libvosk.xcframework Artifact
        uses: actions/upload-artifact@v4
        with:
          name: libvosk-ios-xcframework
          path: dist/ios/libvosk-ios-xcframework.zip
          if-no-files-found: error
