name: Build macOS x86_64

on:
  workflow_dispatch:

jobs:
  build-macos-x86_64:
    name: Build macOS x86_64 dylib
    runs-on: macos-13
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make build script executable
        run: chmod +x build_macos_x86_64.sh

      - name: Install build dependencies
        run: |
          brew install autoconf automake libtool sox gcc
          echo "/opt/homebrew/opt/libtool/libexec/gnubin" >> $GITHUB_PATH

      - name: Build x86_64 libvosk.dylib
        run: ./build_macos_x86_64.sh

      - name: Upload x86_64 dylib Artifact
        uses: actions/upload-artifact@v4
        with:
          name: libvosk-macos-x86_64
          path: dist/macos/x86_64/libvosk.dylib
          if-no-files-found: error
